name: validate

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ./tests.sh
